name:                eertree
version:             0.1.0.0
github:              "fizruk/eertree"
license:             BSD3
author:              "Nickolay Kudasov, Timur Khazhiev"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "2019 Nickolay Kudasov, Timur Khazhiev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/eertree#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  eertree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eertree
