name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  stack-test:
    name: Building and testing with Stack
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: 💾 Cache .stack/
        uses: actions/cache@v2
        with:
          path: |
            .stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock', 'eertree.cabal') }}-stack

      - name: 🔨 Build EERTREE (with Stack)
        run: |
          stack build

      - name: 🔨 Run tests (with Stack)
        run: |
          stack test
